name: delightinsynapse

description: >-
  A mobile-first Flutter app to preview all your Rive (.riv) files. Works on Android, iOS, and Web.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add dependencies
dependencies:
  flutter:
    sdk: flutter
  rive: ^0.13.4
  path: ^1.8.3
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/app_icon.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/rive/
    - assets/manifest.json
    - assets/rive_logo.svg
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist/Geist-Regular.ttf
        - asset: assets/fonts/Geist/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geist/Geist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Geist/Geist-SemiBold.ttf
          weight: 600
# Place all your .riv files in assets/rive/
# The manifest.json will be auto-generated in this folder
